// Package agentpod builds the Kubernetes objects the broker is allowed to
// create.
//
// It is the security-critical code on the scarab side: it is where every
// invariant in scarab/docs/architecture.md §4 is either honoured or lost. The design
// rule is that this package can only ever produce a PodSpec from its own
// templates plus task-level inputs. A caller cannot supply a ServiceAccount
// name, a volume, a securityContext, a node selector, or a security-affecting
// label, because Request has no field for any of them.
//
// The invariants are enforced again by the API server (Pod Security Admission
// `restricted` plus the ValidatingAdmissionPolicies in my-opps), so a bug here
// fails at admission rather than becoming a hole. This package exists so that
// failure does not happen in the first place.
package agentpod

import (
	"errors"
	"fmt"
	"regexp"
	"strings"

	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"github.com/gobackto-work/scarab/internal/contract"
)

// Limits on task-level input.
const (
	// MaxTaskBytes bounds the task string. It is passed as a single argv
	// element, so the only cost of a large value is memory.
	MaxTaskBytes = 32 << 10

	// DefaultTimeoutSeconds is used when a request omits a timeout.
	DefaultTimeoutSeconds int32 = 1800

	// MinTimeoutSeconds is the shortest deadline a worker may be given. A caller
	// that asks for less is rejected rather than handed a worker that cannot
	// possibly finish: a single model call takes longer than a few seconds, so a
	// tiny deadline is a guaranteed failure with a confusing symptom (the worker
	// disappears with no result). Seen live, when an agent chose 15s.
	MinTimeoutSeconds int32 = 60

	// MaxTimeoutSeconds caps a worker's lifetime.
	MaxTimeoutSeconds int32 = 24 * 60 * 60

	// DefaultJobTTLSeconds is how long a finished Job is retained so the 20-job
	// quota does not fill with history.
	DefaultJobTTLSeconds int32 = 300
)

// Resource defaults. The requests are the LimitRange defaults; the limits are
// the values in handoff §5.7. A request may raise its limits, within the
// LimitRange maximum carried in Config.
const (
	defaultRequestCPU    = "100m"
	defaultRequestMemory = "256Mi"
	defaultLimitCPU      = "300m"
	defaultLimitMemory   = "512Mi"

	scratchSizeLimit = "512Mi"
	tmpSizeLimit     = "256Mi"
)

// AgentID bounds. The id is generated by the broker and is opaque to the agent;
// it must keep "worker-<id>" within the 63-character label limit.
const (
	MinAgentIDLen = 8
	MaxAgentIDLen = 26
)

var agentIDRE = regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`)

// Config is the trusted, broker-supplied configuration. None of it comes from
// the agent.
type Config struct {
	// Namespace is the tenant namespace, ws-<slug>.
	Namespace string

	// Workspace is the slug. It becomes the value of the workspace label, which
	// the tenant's network policies match on.
	Workspace string

	// Image is the agent image reference.
	Image string

	// SAWorker is the ServiceAccount for worker pods. It must be pi-worker.
	SAWorker string

	// ResultRoot is the directory, on the shared volume, under which each worker
	// writes <agent-id>/result.md. Defaults to contract.ResultRoot.
	ResultRoot string

	// MaxCPU and MaxMemory mirror the workspace LimitRange per-container
	// maximum. A request that exceeds them is rejected before it reaches the API
	// server.
	MaxCPU    resource.Quantity
	MaxMemory resource.Quantity

	// RunAsUser, when non-nil, pins the container UID. The image must have a
	// matching non-root user, or the pod will not start.
	RunAsUser *int64

	// JobTTLSeconds is how long a finished Job is retained. Zero uses
	// DefaultJobTTLSeconds.
	JobTTLSeconds int32

	// MountMemory mounts the optional /memory PVC. Workers normally do not.
	MountMemory bool
}

// DefaultConfig returns the production defaults for one workspace. The caller
// supplies the namespace, slug and image; everything else matches
// scarab/docs/architecture.md §4.3 and §5.7.
//
// There is no model-credential parameter: the MVP credential is supplied by the user
// in the session and persisted to the shared agent directory, which workers inherit.
// A Secret delivered via envFrom was a third mechanism for the same thing and is
// gone from both sides.
func DefaultConfig(namespace, workspace, image string) Config {
	return Config{
		Namespace:     namespace,
		Workspace:     workspace,
		Image:         image,
		SAWorker:      contract.SAWorker,
		ResultRoot:    contract.ResultRoot,
		MaxCPU:        resource.MustParse("1"),
		MaxMemory:     resource.MustParse("2Gi"),
		JobTTLSeconds: DefaultJobTTLSeconds,
		// Numeric, and matching the image's numeric USER. With runAsNonRoot the
		// kubelet cannot verify a *named* user from the image config, so the pod is
		// refused with "image has non-numeric user".
		RunAsUser: int64Ptr(1000),
	}
}

// Request is everything an agent may influence about a worker. Every field is
// task-level. Adding a field here widens the attack surface, so it should be
// deliberate.
type Request struct {
	Task           string
	ModelProfile   string
	Resources      ResourceHints
	Workspace      WorkspaceHints
	TimeoutSeconds int32
}

// ResourceHints are upper bounds the agent may ask for. They are validated
// against Config.MaxCPU / MaxMemory and can never exceed them.
type ResourceHints struct {
	CPU    string
	Memory string
}

// WorkspaceHints describe how the worker sees the shared workspace. Only the
// documented values are accepted; the mount itself is fixed by the template.
type WorkspaceHints struct {
	Mount string // "" or "shared"
}

// BuildWorkerJob turns a task-level request into the Job the broker will create.
//
// The returned object sets serviceAccountName explicitly, never automounts a
// token, never sets nodeName or runtimeClassName, mounts only allowlisted volume
// types, and carries a container securityContext that satisfies Pod Security
// Admission `restricted`. Those properties are asserted by the tests in this
// package.
func BuildWorkerJob(agentID string, req Request, cfg Config) (*batchv1.Job, error) {
	if err := validateAgentID(agentID); err != nil {
		return nil, err
	}
	if err := cfg.validate(); err != nil {
		return nil, err
	}
	if err := req.validate(); err != nil {
		return nil, err
	}

	requests, limits, err := resolveResources(req.Resources, cfg)
	if err != nil {
		return nil, err
	}

	timeout := req.TimeoutSeconds
	if timeout == 0 {
		timeout = DefaultTimeoutSeconds
	}
	ttl := cfg.JobTTLSeconds
	if ttl == 0 {
		ttl = DefaultJobTTLSeconds
	}

	backoffLimit := int32(0) // fire-and-forget; a retry would burn the pod budget
	activeDeadline := int64(timeout)

	labels := map[string]string{
		contract.LabelWorkspace: cfg.Workspace,
		contract.LabelComponent: contract.ComponentWorker,
		contract.LabelManagedBy: contract.ManagedByScarab,
	}

	return &batchv1.Job{
		TypeMeta: metav1.TypeMeta{APIVersion: "batch/v1", Kind: "Job"},
		ObjectMeta: metav1.ObjectMeta{
			Name:        "worker-" + agentID,
			Namespace:   cfg.Namespace,
			Labels:      labels,
			Annotations: map[string]string{contract.AnnotationTask: req.Task},
		},
		Spec: batchv1.JobSpec{
			BackoffLimit:            &backoffLimit,
			ActiveDeadlineSeconds:   &activeDeadline,
			TTLSecondsAfterFinished: &ttl,
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{Labels: labels},
				Spec:       workerPodSpec(agentID, req, cfg, requests, limits),
			},
		},
	}, nil
}

// workerPodSpec builds the pod template.
//
// Extracted so BuildWorkerJob stays short enough to read at a glance. This is
// where every §4 invariant either holds or is lost, so it is worth being one
// thing that can be audited in full.
func workerPodSpec(agentID string, req Request, cfg Config, requests, limits corev1.ResourceList) corev1.PodSpec {
	resultPath := strings.TrimSuffix(cfg.ResultRoot, "/") + "/" + agentID + "/result.md"
	return corev1.PodSpec{
		ServiceAccountName:           cfg.SAWorker,
		AutomountServiceAccountToken: boolPtr(false),
		RestartPolicy:                corev1.RestartPolicyNever,
		SecurityContext:              podSecurityContext(cfg),
		Containers: []corev1.Container{{
			Name:  "worker",
			Image: cfg.Image,
			// Exec form, task as one argv element after "--": no shell, and a task
			// beginning with "-" cannot be read as a flag. The entrypoint creates
			// the result directory, then execs pi.
			Command:         []string{contract.AgentEntrypoint, "-p", "--", req.Task},
			Env:             workerEnv(agentID, resultPath),
			Resources:       corev1.ResourceRequirements{Requests: requests, Limits: limits},
			VolumeMounts:    volumeMounts(cfg),
			SecurityContext: containerSecurityContext(),
		}},
		Volumes: volumes(cfg),
	}
}

// ---------------------------------------------------------------------------
// validation
// ---------------------------------------------------------------------------

func validateAgentID(id string) error {
	if len(id) < MinAgentIDLen || len(id) > MaxAgentIDLen {
		return fmt.Errorf("agent id must be %d-%d characters, got %d", MinAgentIDLen, MaxAgentIDLen, len(id))
	}
	if !agentIDRE.MatchString(id) {
		return fmt.Errorf("agent id %q is not a lowercase alphanumeric DNS label", id)
	}
	return nil
}

func (c Config) validate() error {
	switch {
	case c.Namespace == "":
		return errors.New("config: namespace is required")
	case c.Workspace == "":
		return errors.New("config: workspace slug is required")
	case c.Image == "":
		return errors.New("config: agent image is required")
	case c.SAWorker != contract.SAWorker:
		// A worker Job must use pi-worker. The admission policy allows pi-root
		// too, but a worker has no business with the root identity.
		return fmt.Errorf("config: worker service account must be %q, got %q", contract.SAWorker, c.SAWorker)
	case c.MaxCPU.IsZero() || c.MaxMemory.IsZero():
		return errors.New("config: MaxCPU and MaxMemory are required")
	}
	return nil
}

func (r Request) validate() error {
	if strings.TrimSpace(r.Task) == "" {
		return errors.New("task is required")
	}
	if len(r.Task) > MaxTaskBytes {
		return fmt.Errorf("task is %d bytes, maximum is %d", len(r.Task), MaxTaskBytes)
	}
	if r.TimeoutSeconds < 0 {
		return fmt.Errorf("timeoutSeconds must not be negative, got %d", r.TimeoutSeconds)
	}
	if r.TimeoutSeconds > 0 && r.TimeoutSeconds < MinTimeoutSeconds {
		return fmt.Errorf("timeoutSeconds %d is too short; a worker needs at least %d seconds", r.TimeoutSeconds, MinTimeoutSeconds)
	}
	if r.TimeoutSeconds > MaxTimeoutSeconds {
		return fmt.Errorf("timeoutSeconds %d exceeds maximum %d", r.TimeoutSeconds, MaxTimeoutSeconds)
	}
	switch r.Workspace.Mount {
	case "", "shared":
	default:
		return fmt.Errorf("unsupported workspace mount %q", r.Workspace.Mount)
	}
	return nil
}

// resolveResources turns the agent's hints into concrete requests and limits,
// refusing anything above the LimitRange maximum. Requests fall back to the
// LimitRange defaults and are never above the limits.
func resolveResources(hints ResourceHints, cfg Config) (corev1.ResourceList, corev1.ResourceList, error) {
	limitCPU := resource.MustParse(defaultLimitCPU)
	if hints.CPU != "" {
		q, err := resource.ParseQuantity(hints.CPU)
		if err != nil {
			return nil, nil, fmt.Errorf("resources.cpu %q: %w", hints.CPU, err)
		}
		limitCPU = q
	}
	limitMemory := resource.MustParse(defaultLimitMemory)
	if hints.Memory != "" {
		q, err := resource.ParseQuantity(hints.Memory)
		if err != nil {
			return nil, nil, fmt.Errorf("resources.memory %q: %w", hints.Memory, err)
		}
		limitMemory = q
	}

	if limitCPU.Cmp(cfg.MaxCPU) > 0 {
		return nil, nil, fmt.Errorf("resources.cpu %s exceeds the workspace maximum %s", limitCPU.String(), cfg.MaxCPU.String())
	}
	if limitMemory.Cmp(cfg.MaxMemory) > 0 {
		return nil, nil, fmt.Errorf("resources.memory %s exceeds the workspace maximum %s", limitMemory.String(), cfg.MaxMemory.String())
	}

	reqCPU := resource.MustParse(defaultRequestCPU)
	if reqCPU.Cmp(limitCPU) > 0 {
		reqCPU = limitCPU.DeepCopy()
	}
	reqMemory := resource.MustParse(defaultRequestMemory)
	if reqMemory.Cmp(limitMemory) > 0 {
		reqMemory = limitMemory.DeepCopy()
	}

	requests := corev1.ResourceList{
		corev1.ResourceCPU:    reqCPU,
		corev1.ResourceMemory: reqMemory,
	}
	limits := corev1.ResourceList{
		corev1.ResourceCPU:    limitCPU,
		corev1.ResourceMemory: limitMemory,
	}
	return requests, limits, nil
}

// ---------------------------------------------------------------------------
// template pieces
// ---------------------------------------------------------------------------

func boolPtr(b bool) *bool { return &b }

func int64Ptr(i int64) *int64 { return &i }

// podSecurityContext sets the pod-level half of PSA `restricted`. Seccomp and
// runAsNonRoot are set at the pod level so they are inherited even if a
// container-level context were ever dropped.
func podSecurityContext(cfg Config) *corev1.PodSecurityContext {
	sc := &corev1.PodSecurityContext{
		RunAsNonRoot:   boolPtr(true),
		SeccompProfile: &corev1.SeccompProfile{Type: corev1.SeccompProfileTypeRuntimeDefault},
	}
	if cfg.RunAsUser != nil {
		uid := *cfg.RunAsUser
		sc.RunAsUser = &uid
	}
	return sc
}

// containerSecurityContext sets the container-level half of PSA `restricted`.
//
// readOnlyRootFilesystem is deliberately NOT set: the root bridge and the worker
// run the same scarab-agent image, and pestilence's root template leaves the root
// filesystem writable. Setting it only on workers would diverge from the image
// that actually runs. Revisit as hardening once the image's writable paths are
// known.
func containerSecurityContext() *corev1.SecurityContext {
	return &corev1.SecurityContext{
		RunAsNonRoot:             boolPtr(true),
		AllowPrivilegeEscalation: boolPtr(false),
		Capabilities:             &corev1.Capabilities{Drop: []corev1.Capability{"ALL"}},
		SeccompProfile:           &corev1.SeccompProfile{Type: corev1.SeccompProfileTypeRuntimeDefault},
	}
}

// workerEnv is the worker's environment. No credential appears here: the model key
// lives in the shared agent directory, which Pi reads, and the capability token is
// deliberately not given to a worker at all.
func workerEnv(agentID, resultPath string) []corev1.EnvVar {
	return []corev1.EnvVar{
		{Name: contract.EnvAgentID, Value: agentID},
		{Name: contract.EnvResultPath, Value: resultPath},
		{Name: contract.EnvSessionDir, Value: contract.MountScratch + "/pi"},
		{Name: contract.EnvAgentDir, Value: contract.AgentDir},
		{Name: contract.EnvHome, Value: contract.MountScratch},
	}
}

func volumeMounts(cfg Config) []corev1.VolumeMount {
	mounts := []corev1.VolumeMount{
		{Name: contract.NameWorkspacePVC, MountPath: contract.MountWorkspace},
		{Name: "scratch", MountPath: contract.MountScratch},
		{Name: "tmp", MountPath: contract.MountTmp},
	}
	if cfg.MountMemory {
		mounts = append(mounts, corev1.VolumeMount{Name: contract.NameMemoryPVC, MountPath: contract.MountMemory})
	}
	return mounts
}

// volumes uses only types on the admission allowlist: persistentVolumeClaim and
// emptyDir. No hostPath, secret, configMap or projected volume is ever emitted.
func volumes(cfg Config) []corev1.Volume {
	scratchLimit := resource.MustParse(scratchSizeLimit)
	tmpLimit := resource.MustParse(tmpSizeLimit)
	vols := []corev1.Volume{
		{
			Name: contract.NameWorkspacePVC,
			VolumeSource: corev1.VolumeSource{
				PersistentVolumeClaim: &corev1.PersistentVolumeClaimVolumeSource{ClaimName: contract.NameWorkspacePVC},
			},
		},
		{
			Name: "scratch",
			VolumeSource: corev1.VolumeSource{
				EmptyDir: &corev1.EmptyDirVolumeSource{SizeLimit: &scratchLimit},
			},
		},
		{
			Name: "tmp",
			VolumeSource: corev1.VolumeSource{
				EmptyDir: &corev1.EmptyDirVolumeSource{SizeLimit: &tmpLimit},
			},
		},
	}
	if cfg.MountMemory {
		vols = append(vols, corev1.Volume{
			Name: contract.NameMemoryPVC,
			VolumeSource: corev1.VolumeSource{
				PersistentVolumeClaim: &corev1.PersistentVolumeClaimVolumeSource{ClaimName: contract.NameMemoryPVC},
			},
		})
	}
	return vols
}
